### ISSUE TITLE
again login errors，This is why？Thank！

### ISSUE THREAD

**Issue by symphonyh** [arturaum/user_events#1]
note：
--- !ruby/hash-with-ivars:ActionController::Parameters
elements:
  utf8: "✓"
  authenticity_token: JAq0a6cO0QJCVQg6trZ7UJkavk8vg1uWJ64DLDOLFYPhJMBxH1uA9HgxTZ3SYMhJtas0XoSQM/dBIvJRaJNr/A==
  user_session: !ruby/hash-with-ivars:ActionController::Parameters
    elements:
      email: hxy@163.com
      password: '123456'
    ivars:
      :@permitted: false
  commit: Login
  controller: user_sessions
  action: create
ivars:
  :@permitted: false

**Comment by arturaum** [comment]
You can create user in console. Plus take a look to authlogic gem documentation

**Comment by symphonyh** [comment]
The problem is "Strong Parameter ". thank!!!
use version: ruby 2.3.3 rails 4.2.5
update code:

```
class UserSessionsController < ApplicationController

  def new
    @user_session = UserSession.new
  end
  
  def create

    # remove rows @user_session = UserSession.new(params[:user_session])
    @user_session = UserSession.new(user_session_params)
     if @user_session.save
      flash[:notice] = "Successfully logged in."
      redirect_to root_url
    else
      render :new
    end
  end

  def destroy
    @user_session = UserSession.find
    if @user_session
      @user_session.destroy
      flash[:notice] = "Successfully logged out."
    end
    redirect_to root_url
  end


  # add Strong Parameter Method：
 private
  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
  
end
```
